# Generated by Django 3.0.3 on 2020-03-03 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapData',
            fields=[
                ('map_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('data_url', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=64)),
                ('longtitude', models.CharField(max_length=64)),
                ('date_created', models.DateTimeField()),
                ('data_modified', models.DateTimeField()),
            ],
        ),
    ]
