# Generated by Django 3.0.3 on 2020-05-23 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(blank=True, max_length=50)),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MapHandlerProcessing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('huc_12', models.CharField(blank=True, max_length=64)),
                ('fishnet_1', models.IntegerField(blank=True)),
                ('fishnet_2', models.IntegerField(blank=True)),
                ('fishnet_3', models.IntegerField(blank=True)),
                ('fishnet_4', models.IntegerField(blank=True)),
                ('fishnet_5', models.IntegerField(blank=True)),
                ('status', models.CharField(max_length=32)),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MapData',
            fields=[
                ('data_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('data_url', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=64)),
                ('longitude', models.CharField(max_length=64)),
                ('fishnet_1', models.IntegerField(null=True)),
                ('fishnet_2', models.IntegerField(null=True)),
                ('fishnet_3', models.IntegerField(null=True)),
                ('fishnet_4', models.IntegerField(null=True)),
                ('fishnet_5', models.IntegerField(null=True)),
                ('huc_4', models.CharField(max_length=64, null=True)),
                ('huc_6', models.CharField(max_length=64, null=True)),
                ('huc_8', models.CharField(max_length=64, null=True)),
                ('huc_10', models.CharField(max_length=64, null=True)),
                ('huc_12', models.CharField(max_length=64, null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('file_location', models.FileField(default=None, upload_to='uploaded/')),
                ('method', models.TextField(blank=True)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('begin_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('access_group', models.ManyToManyField(blank=True, to='auth.Group')),
                ('author', models.ManyToManyField(blank=True, to='dataPortal.Author')),
                ('tags', models.ManyToManyField(to='dataPortal.Tag')),
                ('uploader', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
