# Generated by Django 3.0.3 on 2020-03-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataPortal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapdata',
            name='extra_data',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mapdata',
            name='file_location',
            field=models.FileField(default=None, upload_to='uploaded/'),
        ),
    ]
