# Generated by Django 3.0.3 on 2020-06-08 00:03

import dataPortal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('dataPortal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapdata',
            name='access_group',
            field=models.ManyToManyField(to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='mapdata',
            name='file_location',
            field=models.FileField(default=None, upload_to=dataPortal.models.uuid_filename),
        ),
    ]
